# Generated by Django 2.1.3 on 2018-11-24 19:45

from django.db import migrations, models
import food_watch.models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food_watch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureevent',
            name='metadata',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pictureevent',
            name='picture',
            field=models.ImageField(upload_to=food_watch.models.picture_path),
        ),
    ]
