# Generated by Django 2.1.3 on 2018-11-25 05:49

from django.db import migrations, models
import django.db.models.deletion
import food_watch.models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food_watch', '0002_auto_20181124_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicturePatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('picture', models.ImageField(upload_to=food_watch.models.picture_path)),
                ('metadata', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='pictureevent',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='pictureevent',
            name='picture',
        ),
        migrations.AddField(
            model_name='picturepatch',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='food_watch.PictureEvent'),
        ),
    ]
